[package]
name = "emergence_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
color-eyre = "0.6.5"
emergence_zk = {path="../emergence_zk"}
serde = "1.0.227"
tokio = { version = "1.48.0", features = ["full"] }

[lints]
workspace = true
