//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

pub use super::tag::Entity as TagEntity;
pub use super::zettel::Entity as ZettelEntity;
pub use super::zettel_tag::Entity as ZettelTag;
